### ISSUE TITLE
Robert

### ISSUE THREAD

**Issue by ryinnthedk** [robertvandervoort/SmartThings#11]
Thank you for your work on the Doorbell.  I followed the instruction directly on Smartthings and on Aeon's site.  I just can't seem to get notifications working, and the settings don't seem to be updating the device either.  I push the doorbell - I still hear sound 1, and it still rings 2 times, despite what I've setup in  settings.  I bought the doorbell in hopes that I can connect to SmartThings and get a simple push notification - but the "Notify me When" app doesn't work.  Any help?

**Comment by tcsmith11** [comment]
I found that after changing the device type, the device in graph.api.smartthings.com had some weirdness related to the previous device type.   Logging in online allowed me to change settings there and after that everything worked.  Sorry for the lack of technical description - its been a while but I do remember getting it working by logging in to the web interface.
