### ISSUE TITLE
Aeon Doorbell - error creating in IDE

### ISSUE THREAD

**Issue by charlesjhking** [robertvandervoort/SmartThings#12]
I am trying to create a new SmartApp in my IDE from your code "V 0.3 of Aeon Doorbell code 11/24/2015".  When I cut and paste the code and click "Create" the following error appears at the top of the page:

No signature of method: script14572996593901384936853.metadata() is applicable for argument types: (script14572996593901384936853$_run_closure1) values: [script14572996593901384936853$_run_closure1@5e89b807] Possible solutions: getMetadata(), getState(), getbatt(), setState(java.lang.Object), metaClass(groovy.lang.Closure) 

With this error I am unable to proceed to publish.

Tried v2 and v1 of your code - same result.

I am very much a novice user and I have no coding experience.  Not sure if this is something I am doing wrong (although I have create several SmartApps via "cut and paste" like this before without issue), or a typo in the code that someone who understands code could readily fix, or what.  Hope you can advise.

(PS: I am hoping this code/SmartApp will allow me to use a MyQ sensor on my garage door [already integrated via another SmartApp] to trigger the Aeon Doorbell when the garage door first opens, and not repeatedly trigger the doorbell while the door is open.)

**Comment by robertvandervoort** [comment]
You need to create a device type not a smart app. That's the issue.

**Comment by charlesjhking** [comment]
Thank you!  That worked.  

 

Charles King

 <mailto:Charlesjhking@gmail.com> Charlesjhking@gmail.com
