### ISSUE TITLE
com.netflix.hystrix.exception.HystrixRuntimeException: C*-DeviceDataIndex-Create timed-out and fallback disabled.

### ISSUE THREAD

**Issue by wishbone1138** [robertvandervoort/SmartThings#14]
I'm seeing this error a lot and it appears to be a potential known issue?  Could be a state variable issue?
https://community.smartthings.com/t/hystrix-exception/6927/12

device_type-aeon-multisensor6-v2.2

**Comment by robertvandervoort** [comment]
I am unable to reproduce this.
