### ISSUE TITLE
Incorrect fingerprint causing the SS6 to be recognized as AEON LED Bulbs (next best matching fingerprint)?

### ISSUE THREAD

**Issue by alexruffell** [robertvandervoort/SmartThings#16]
For a while now, whenever I try to do a secure joining of my two AEON Smart Switch 6 they are consistently recognized as AEON Led Bulbs. I read up on fingerprinting and if I understand correctly the old system would find a match between the classes listed in the fingerprint and the available device handlers. It doesn't need to be a complete match and it settles on the one that has the most matching elements. Even a single class listed in the fingerprint that should not be there will prevent the device handler from being selected.

I am suspecting that there is something wrong in the fingerprint of your device handler but I do not know what. Following the very basic instructions in the following post I reconstructed what I believe to be the correct fingerprint (at some point this only worked with hub v2, but ST may have added this to v1 as well - do not know).

Once I changed the fingerprint in your device handler as shown below, ST was actually able to find the correct device handler. I am certain there is still something wrong in my fingerprint as I believe it joined using the insecure method and it is stuck in the "not configured yet" mode... so I also can't access the 'gear' settings page. However the device seems to work.

Could you kindly review the fingerprinting so that ST can actually recognize the device for what it is?

https://community.smartthings.com/t/new-z-wave-fingerprint-format/48204

        /*
            Z-Wave Command Classes
            Model: Smart Switch 6 (ZW096-A02)
            Z-Wave Certification Number: ZC10-15050012

            Supported Command Classes 

                    0x27 All Switch 
                    0x85 Association 
                    0x59 Association Group Information 
                    0x20 Basic 
                    0x81 Clock 
                    0x33 Color Switch (could it be Color Control??)
                    0x70 Configuration 
                    0x5A Device Reset Local 
                    0x7A Firmware Update Meta Data 
                    0x72 Manufacturer Specific 
		    0x32 Meter 
                    0x73 Powerlevel 
                    0x98 Security 
                    0x25 Switch Binary 
                    0x26 Switch Multilevel 
                    0x86 Version 
                    0x5E ZWavePlus Info 

            Controlled Command Classes 

                    0x20 Basic 
                    0x82 Hail 
                    0x25 Switch Binary 
*/

		//zw:Ls type:1001 mfr:0086 prod:0103 model:0060 ver:1.03 zwv:4.05 lib:03 cc:5E,86,72,98 ccOut:5A,82 sec:25,26,33,70,27,32,81,85,59,7A,73 role:05 ff:8700 ui:8700
               //zw:L type:1001 mfr:0086 prod:0103 model:0060 ver:1.03 zwv:4.05 lib:03 cc:5E,25,26,33,70,27,32,81,85,59,72,86,7A,73,98 ccOut:5A,82 role:05 ff:8700 ui:8700

		//fingerprint deviceId: "0x1001", inClusters: "0x98"
        //fingerprint inClusters: "0x25,0x26,0x27,0x32,0x2C,0x2B,0x33,0x85,0x56,0x59,0x5A,0x5E,0x70,0x72,0x73,0x85,0x86", outClusters: "0x82"
        fingerprint mfr: "0086", prod: "0103", model: "0060"
        fingerprint type: "8700", cc: "5E,25,70,27,81,32,26,33,59,85,72,86,7A,73,98,5A,82" //Leaving out EF in cc as it doesn't appear in Raw Description
        fingerprint cc: "5E,86,72,98", sec: "25,26,33,70,27,32,81,85,59,7A,73", secOut:"5A,82" //Leaving out EF in cc as it doesn't appear in Raw Description

**Comment by robertvandervoort** [comment]
Sorry to hear the troubles. I made this against a pre-production switch so
it is quite possibly different in a few ways. Unfortunately my switch died
after only a couple months operating an air filter I have in my bedroom.
When it did work it had recognized and joined it perfectly. So as such I've
nothing to test against. Feel free to branch the code.
