### ISSUE TITLE
Question : Does your code work with updated firmware 1.07

### ISSUE THREAD

**Issue by cvee72** [robertvandervoort/SmartThings#17]
Hi,
I recently updated ONE of my multisensor6 firmwares to 1.07 which fixes the following : 
1. Lux and UV accuracy/sensitivity improved
2. Accuracy of Temperature and Humidity sensor accuracy improved while used on USB power
3. Added Configuration settings and changes

I had to reset the sensor before firmware update... so when added back to ST hub it defaulted to the standard device handler.. after which i linked it to your code :- Aeon Multisensor 6 - RV 2.3

Although the device appears operational, when i go to device settings via ST app I can see that there are 3 NULL parameters AFTER Report data interval.

On my non upgraded multisensor6 (with your code) I see 10 additional parameters values AFTER Report data interval.

Also it seems although i have setup a humidity offset.... the offset value is not being reflected.

So this is just a quick check to see if you have tested... or heard of anyone else using your code with updated multisensor6 firmware.

From IDE this is what Preferences i see in each case using your device handler code.
# **Pre firmware update (on 1.06)**

Name    Type    Value
HumidChangeAmount       10
HumidOffset         0
IllumChangeAmount       10
MotionReset     number  20
PIRsensitivity  number  3
ReportingInterval   number  300
TempChangeAmount        2
TempOffset      0
debugOutput     boolean     false
humidityoffset  number  3
luminanceoffset     number  0
motionDelayTime         30 seconds
motionSensitivity       3
reportInterval      5 minutes
tempScale       C
tempoffset  number  -4
tzOffset        -10
ultravioletoffset   number  0
## **Post firmwmare update (on 1.07) :-** 

Name    Type    Value
MotionReset     number  20
PIRsensitivity  number  1
ReportingInterval   number  300
debugOutput     boolean     false
humidityoffset  number  -3
luminanceoffset     number  0
motionDelayTime         null
motionSensitivity       null
reportInterval      null
tempoffset  number  0
ultravioletoffset   number  0

Cheers
cvee

**Comment by robertvandervoort** [comment]
GREAT question.

I'm not sure. Mine are still on old firmware. I should get with my contact
at Aeotec to get the new firmware loaded up and find out.

It is quite likely the parameter numbers may have changed or something that
would make it not work as expected.

I'll try and find out for you soon. If you don't hear back from me by
Friday, hit me up again. They are usually pretty responsive.

~R

**Comment by robertvandervoort** [comment]
So I went through the new spec sheet. I hadn't bothered upgraded because mine has always worked and you know what they say... Anyhow, there are TONS of changes and added parameters. I'll take a bit to go through them to see if there is anything meriting inclusion or that would change operation at all. I've also reached out to get the new firmware. Where did you get the new firmware from?

**Comment by cvee72** [comment]
Hi,
  
The firmware is available via the aotec website. 
http://aeotec.com/support

I only updated 1 of my 4 sensors to see if the temp accuracy had changed.  The new firmware is supposed to fix the accuracy of the light and temp sensors. 

Not sure if they have hidden any extra goodies in there.

**Comment by robertvandervoort** [comment]
to be clear, the proper firmware is here:
https://aeotec.freshdesk.com/support/solutions/articles/6000036562-multisensor-6-firmware-update-6-17-2016-

working on it now.

**Comment by robertvandervoort** [comment]
@cvee72 did you check out EROCM123's device type? It's already compatible up to 1.8 and has a load of great features. https://github.com/erocm123/SmartThingsPublic/blob/master/devicetypes/erocm123/aeon-multisensor-6-advanced.src/aeon-multisensor-6-advanced.groovy

Also how did you do your firmware update? Did you use a Z-Stick?

**Comment by cvee72** [comment]
Hi,
I'll check out the alternative device type. I was not aware of it. 
I used a z-stick and followed aotec instructions to update firmware.
