### ISSUE TITLE
Compile Error: Aeon Smart Switch 6-v0.4 ANDROID

### ISSUE THREAD

**Issue by tcsmith11** [robertvandervoort/SmartThings#18]
Hi Robert, 
SmartThings/Aeon SmartSwitch 6/device_type-aeon-smartswitch6-v0.4-ANDROID gives a compile error when adding a DTH to the IDE: 

org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
script14862343877762075700318.groovy: 100: expecting '}', found ',' @ line 100, column 26.
input "monitorInterval", "integer", 
^

1 error

**Comment by robertvandervoort** [comment]
My bad. Removed the stray comma, all is compiling now... Thanks for the reminder.
