### ISSUE TITLE
How well and often does it report lux?

### ISSUE THREAD

**Issue by newelement** [robertvandervoort/SmartThings#2]
Using the battery only, how often does it report the lux. Also, can it be configured through the ST app?

**Comment by robertvandervoort** [comment]
it reports lux only if it changes by 100 lux or more, and it would report every hour. I'm working with Aeotech to get the parameters around offsets and sensitivity working, as it seems there was some misprints in the documentation. Once I get that bit of the code sorted out everything from the preferences section should work in the app.

**Comment by robertvandervoort** [comment]
in case you haven't been following the forum, it is reporting at 5 minute intervals now in the 1.4 code. the preference for reporting interval is also now working. Any changes you make require a double tap on teh action button and to press the config button in the device screen in the app. Currently working a new issue with temp offset not going negative.
