### ISSUE TITLE
When dimmer is off, moving the dimmer slider does not turn the status to ON

### ISSUE THREAD

**Issue by nivw** [robertvandervoort/SmartThings#21]
robertvandervoort : Aeon Smart Dimmer 6 - RV v0.1

**Comment by robertvandervoort** [comment]
I am unable to reproduce this issue. Moving my slider when the device is off turns the device on and sets the level. Can you please re-verify your finding, and if it still exists, let me know what firmware version of the switch and what hub version you're using and is this on Android or IOS?
