### ISSUE TITLE
Zooz 4 N 1 Default tile change

### ISSUE THREAD

**Issue by jdigangi** [robertvandervoort/SmartThings#23]
Is it possible to change the default tile view in the Zooz 4 n 1 device handler?  Currently by default its motion i would like to change it to temperature if possible.  I tried editing the default primarytile options but i was unsuccessful.

SM>My HOME>THINGS> Sensor  Value

Thanks
James

**Comment by robertvandervoort** [comment]
Yeah no big deal. I have two files in the folder - https://github.com/robertvandervoort/SmartThings/tree/master/zooZ-4-in-1-Sensor-ZSE40

one has "motion primary" on the end of it, the other uses temp as primary, just use that code for your device handler.

**Comment by jdigangi** [comment]
Absolutely perfect – Thank you!

**Comment by robertvandervoort** [comment]
cool. no problem. I like temp as primary too.
