### ISSUE TITLE
Device only reporting Lux, Temperature, etc 1x per hour despite seeing 300 seconds in code

### ISSUE THREAD

**Issue by mikelupo** [robertvandervoort/SmartThings#4]
Hi Robert,
I have integrated v1.4 of your Device Type (Thank you for this by the way!).
I noticed that I only get 1 update per hour despite the fact that you've set it up to wake up every 5 minutes and report values back. I could use to help debugging that.

Also, one other thing (it's by design I think). If the illuminance has not changed since the last wake up, it's not reported. That is causing me some issues as it can go many hours between illuminance events.  Can there be an option to have it report status no matter what the last status was?

The folks at Aeon support want to me to feedback the findings to them. 

Thanks in advance,
Mike

**Comment by robertvandervoort** [comment]
Threshold based reporting is enabled in the device by default. It can be
added to the code to turn it off pretty straightforward. For some reason my
sensor stopped letting me configure it. I need to do some troubleshooting
but I'm off at PASS Summitt in Sesttle all this week.

**Comment by mikelupo** [comment]
Thanks!
With ST, can we update the device remotely or do I need a flashing app and USB cable?

**Comment by robertvandervoort** [comment]
Firmware wise or setting wise? Settings like threshold and so forth are
over the air. The firmware update over the air isn't supported by smart
things y t you'd have to get an aeon z stick or similar. Honestly I
wouldn't bother though there's not enough that matters in the new fw.

**Comment by mikelupo** [comment]
Hi Robert,
Setting-wise (not FW). Basically, in order to configure the device behaviors. 
What I don't understand by looking at the code is how you currently configure the device.
I do software for a living, but looking at this device type, I can't seem to reverse engineer it by just looking at it.


Stating it another way, I do not know how to apply what I see in the .pdf document to the code.


I realize you're busy at a show right now, and this can certainly wait, but I'd like to nail this down when you can spend a few short cycles on it., Namely, figuring out why Illuminance reports every hour instead of 5 minutes and how to disable the "selective reporting" feature.


Thanks again!
Mike







-----Original Message-----
