### ISSUE TITLE
Can't pair Multisensor 6 with SmartThings

### ISSUE THREAD

**Issue by gregg-iotas** [robertvandervoort/SmartThings#5]
Where is the "inclusion button"? The Multisensor 6 doesn't have any physical buttons and the SmartThings Hub only has a reset button. If I try to pair a new device on the SmartThings hub the hub doesn't see the sensor.

**Comment by robertvandervoort** [comment]
There is a dimple on the back of the sensor. It's in the instruction manual
that it ships with but yeah, that got me too, you go into smart things app
add new device the quickly double tap the dimpled corner on the sensor to
join it. Then you have to login to the developer site and swap the device
type out for mine or bs87s version of mine.

**Comment by gregg-iotas** [comment]
Thanks! I was able to pair sensor and swap out the device handlers with yours.

I am having a little trouble adjusting the settings on the sensor. The sensor is reading 6 degrees hotter temp than it should so I tried to follow your instructions of making the change in the setting on the app then pressing the dimple on the back of the sensor then hitting save on the app. I see the error on the app saying that I have not filled in all the required fields. I checked the live log to see if the changes was registered but I don't see it there. Is there a step I am missing?

**Comment by mikelupo** [comment]
Just to whine a little.
I can't get my MS6 to give me Lux and Temperature updates quicker that 1/hour. 
I need to follow up with Robert Vandervoort again as he is the author of the Device Type I'm using. I did reach out to him but he was on the road. That was a few weeks ago. 





-----Original Message-----

**Comment by gregg-iotas** [comment]
The temp sensor started reading correctly on its own. Now i'm stuck on trying to get the vibration sensor to be seen as a trigger for events.

**Comment by robertvandervoort** [comment]
Hey I know we talked on the community site. Haven't been watching my github comments :)

If you watch it on the app, and you whack the sensor, do you see the tamper tile go red at least? this is the first step..

I made a custom capability so it probably wont be recognized. It is likely I will have to change it to activate the acceleration capability. I just need to know what capability the smart app you're trying to use against it expects to see. Can you link me to it?

**Comment by gregg-iotas** [comment]
https://play.google.com/store/apps/details?id=com.smartthings.android&hl=en
This is the app I am using. There in the SmartThings app under home security there is option to add a custom monitoring rule and in there you can add
![sensors](https://cloud.githubusercontent.com/assets/15694141/11072563/40337364-879b-11e5-91c5-ac5b186396f0.png)
 a vibration sensor. What am trying to do is trigger events( ie turn on a light) when vibration/tamper/acceleration is detected. I mounted the sensor to a door and I want to see if the sensor will pick up the vibration of the door opening/closing.

**Comment by robertvandervoort** [comment]
best I can tell it relies on the acceleration sensor class. I'll switch it up tonight when I get off work and message you.

**Comment by gregg-iotas** [comment]
Awesome!

**Comment by robertvandervoort** [comment]
There you go sir. Version 2.1 tested and working.
