### ISSUE TITLE
Acceleration/tamper sensor not firing

### ISSUE THREAD

**Issue by gregg-iotas** [robertvandervoort/SmartThings#6]
Hi Robert,

I was able to add the sensor as a vibration sensor to SmartThings. However I have been unable to get the sensor to trigger. I can shake the sensor in my hand but I don't see the sensor change state in the live log or when looking at the device directly under My Devices. Do I need to change a setting? I have uninstalled and reinstalled the device.

Cheers
Gregg

**Comment by robertvandervoort** [comment]
this should be fixed.. i had a typo.. copy pasted the wrong tab originally.

**Comment by gregg-iotas** [comment]
I can get the vibration sensor to trigger if I bang on the table with the device on the table :+1:  It doens't trigger on the door swing open or close no matter the speed at which I throw the door open. Is there a way to increase the sensitivity of the sensor?

**Comment by robertvandervoort** [comment]
there is not. besides opening it up and replacing the shock sensor with a more sensitive one.
