### ISSUE TITLE
Settings don't seem to change anything

### ISSUE THREAD

**Issue by stephenanspach** [robertvandervoort/SmartThings#9]
Just got 3 MS6's and all exhibit the same behavior.  I'm using v2.2 of code and even tried reverting to 2.0 and 1.5 but no change.  Issue is that I set tempoffset either in webapp or ST app to some value but displayed temp never changes.  (using USB reported temps are ~+5F from actual, and when on battery temps are ~-2F.  weird.)

one thing I noticed in the logs is for ENTITY_UPDATE it shows name=DeviceUpdated,changed=false.  does that mean my changes aren't taking?  (b/c that's what it seems like).  I do see the updated values in both the webapp and ST app, but the temp never really offsets.

also much like the OP on the previous thread no matter what I set ReportingInterval to, it only reports every hour.  any help is appreciated.  thanks!

**Comment by robertvandervoort** [comment]
this is not an issue with the code, please PM me or review the comments already posted in the thread on the proper pairing of the sensor. If your sensors only report every hour, your settings are not taking. Open the live logging view in the IDE. Exclude the device from the hub, hold the action button for 30 seconds until it flashes red fast then returns to color cycling to reset the sensor, plug in with usb close to your hub and re add the sensor. After adding. Change device type to my device type, then open the device in the app, go to edit the device, set all of the preferences at once zero or not and turn on the debug logging option, and save. Wait 1 minute then press the config button on the main view of the sensor in the app. This will send a complete array of commands to properly configure the device. You should see each setting be sent and report the current value back in the debug log as settings are sent and checked one by one.

Thanks,

Robert
